apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vis-lb001
  name: vis-lb001
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector: # pod finder dynamically
    app: vis-app-ui  # put label of deployment template at selector
  type: LoadBalancer
status:
  loadBalancer: {}
